= Contributing to Spring Fu

Spring Fu is released under the Apache 2.0 license. If you would like to contribute something, or simply want to hack on the code this document should help you get started.

== Code of Conduct

This project adheres to the Contributor Covenant link:CODE_OF_CONDUCT.adoc[code of conduct]. By participating, you are expected to uphold this code. Please report unacceptable behavior to spring-code-of-conduct@pivotal.io.

== Using GitHub Issues

We use GitHub issues to track bugs and enhancements. If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible.

=== Building from Source
To build the source you will need to install Java 8+, and you will need a local MongoDB server to run tests and samples.

==== Build
The project can be built from the root directory using the standard Gradle command:

[indent=0]
----
	$ ./gradlew build
----

==== Documentation

Documentation can be built via the following Gradle command:

[indent=0]
----
	$ ./gradlew asciidoctor
----

In order to get syntax highlighting for Kotlin code, https://github.com/jirutka/asciidoctor-rouge[asciidoctor-rouge] needs to be installed before running the following command:

[indent=0]
----
	$  asciidoctor -r asciidoctor-rouge -a source-highlighter=rouge src/docs/asciidoc/reference.adoc -o build/docs/html5/reference.html

----
