== Contributing to Spring Fu

Spring Fu is released under the Apache 2.0 license. If you would like to contribute something, or simply want to hack on the code this document should help you get started.

=== Building from Source

To build the source you will need to install Java 11+.

In your IDE import the root project to have Spring Fu, and the `samples` subdirectory to have the samples.
Configure it to use tabs, not spaces.

The project and the samples can be built from the root directory using the following command on Linux/MacOS:

[indent=0]
----
	./build.sh
----

If you prefer using Gradle command or if you are on Windows, to build the project just use:

[indent=0]
----
	./gradlew build
----

If you want to build the project, install the artifacts in the local Maven repository and build samples against it:

[indent=0]
----
	./gradlew -x javadoc build publishToMavenLocal
	cd samples
	./gradlew build
----

=== Release process

Here is the semi-automated release process (to be improved) with `O.x` being the version to release and `0.y` the new version:

* Warn on Slack that the release process starts and that no commit is allowed on `master`.
* Check https://ci.spring.io/teams/spring-fu/pipelines/spring-fu[the CI] is green.
* Replace in the `build.gradle.kts` and `pom.xml` `0.x-SNAPSHOT` by `0.x`
* Set `:spring-fu-version: 0.x` in `jafu/README.adoc` and `kofu/README.adoc`
* `git commit -a -m "Release Spring Fu 0.x"`
* `git tag v0.x`
* `git push`
* `git push --tags`
* Wait the green build on https://ci.spring.io/teams/spring-fu/pipelines/spring-fu[the CI].
* Check the JaFu documentation badge link on https://github.com/spring-projects-experimental/spring-fu/tree/master/jafu and the koFu one on https://github.com/spring-projects-experimental/spring-fu/tree/master/kofu
* https://github.com/spring-projects-experimental/spring-fu/milestones[Close the milestone]
* Publish a https://github.com/spring-projects-experimental/spring-fu/releases/new[new release]:
** Tag: `v0.x`
** Title: `v0.x`
** Bullet point of main features
** Check "This is a pre-release"
* Replace in the `build.gradle.kts` and `pom.xml` `0.x` by `0.y-SNAPSHOT`
* `git commit -a -m "Switch to 0.y-SNAPSHOT"`
* `git push`
* Warn on Slack that the release process is finished and that commits are allowed on `master` again.
* Announce the release (Slack, Twitter, potentially blog post)

=== Contributor License Agreement

If you have not previously done so, please fill out and submit the https://cla.pivotal.io/sign/spring[Contributor License Agreement].

=== Code of Conduct

This project adheres to the Contributor Covenant link:CODE_OF_CONDUCT.adoc[code of conduct]. By participating, you are expected to uphold this code. Please report unacceptable behavior to spring-code-of-conduct@pivotal.io.

=== Using GitHub Issues

We use GitHub issues to track bugs and enhancements. If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible.
