== Contributing to Spring Fu

Spring Fu is released under the Apache 2.0 license. If you would like to contribute something, or simply want to hack on the code this document should help you get started.

=== Building from Source

To build the source you will need to install Java 11+.

In your IDE import the root project to have Spring Fu, and the `samples` subdirectory to have the samples.
Configure it to use tabs, not spaces.

The project and the samples can be built from the root directory using the following command on Linux/MacOS:

[indent=0]
----
	./build.sh
----

If you prefer using Gradle command or if you are on Windows, to build the project just use:

[indent=0]
----
	./gradlew build
----

If you want to build the project, install the artifacts in the local Maven repository and build samples against it:

[indent=0]
----
	./gradlew -x javadoc build publishToMavenLocal
	cd samples
	./gradlew build
----

=== Contributor License Agreement

If you have not previously done so, please fill out and submit the https://cla.pivotal.io/sign/spring[Contributor License Agreement].

=== Code of Conduct

This project adheres to the Contributor Covenant link:CODE_OF_CONDUCT.adoc[code of conduct]. By participating, you are expected to uphold this code. Please report unacceptable behavior to spring-code-of-conduct@pivotal.io.

=== Using GitHub Issues

We use GitHub issues to track bugs and enhancements. If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible.
