:spring-fu-version: 0.2
:kofu-kdoc-url: http://repo.spring.io/milestone/org/springframework/fu/spring-fu-kofu/{spring-fu-version}/spring-fu-kofu-{spring-fu-version}-javadoc.jar!
:framework-kdoc-url: https://docs.spring.io/spring-framework/docs/current/kdoc-api

image:https://ci.spring.io/api/v1/teams/spring-fu/pipelines/spring-fu/badge["Build Status", link="https://ci.spring.io/teams/spring-fu/pipelines/spring-fu"] image:https://img.shields.io/badge/API%20documentation-0.2-blue.svg["API documentation", link="{kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-application-dsl.html"]

Spring Fu is an incubator for Kofu, a set of
Kotlin DSLs like {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-application-dsl.html[`application { }`]
and {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-configuration-dsl/index.html[`configuration { }`]
designed to configure Spring Boot explicitly with code in a declarative way with great
discoverability thanks to auto-complete. In Kofu, "Ko" stands for Kotlin, and "fu" for functional.

It leverages other Spring Kotlin DSLs available in Spring like:

 * https://docs.spring.io/spring/docs/current/spring-framework-reference/languages.html#kotlin-bean-definition-dsl[`beans { }` DSL] from Spring Framework
 * https://docs.spring.io/spring/docs/current/spring-framework-reference/languages.html#router-dsl[`router { }` DSL] from Spring MVC or Spring WebFlux
 * https://github.com/spring-projects-experimental/spring-security-kotlin-dsl[`security { }` DSL] (https://github.com/eleftherias/spring-security/tree/gh-5558-kotlin-dsl[WIP]) from Spring Security

It provides fast startup (40% faster than regular auto-configuration on a minimal Spring MVC app) and low memory consumption.

It is not intended to be used in production yet, but rather to incubate and get feedback and contributions
from the community in order to hopefully reach a point where it can be integrated as
Spring Boot Kotlin DSL.

If you are interested in running Spring application as GraalVM native images see the https://github.com/spring-projects-experimental/spring-graal-native-image[spring-graal-native-image] project.

== Sample application

Here is a sample sample application that is leveraging Spring MVC:

```kotlin
val app = application(WebApplicationType.SERVLET) {
	logging {
		level = LogLevel.DEBUG
	}
	beans {
		bean<SampleService>()
	}
	webMvc {
		port = if (profiles.contains("test")) 8181 else 8080
		router {
			val service = ref<SampleService>()
			GET("/") {
				ok().body(service.generateMessage())
			}
			GET("/api") {
				ok().body(Sample(service.generateMessage()))
			}
		}
		converters {
			string()
			jackson {
				indentOutput = true
			}
		}
	}
}

data class Sample(val message: String)

class SampleService {
	fun generateMessage() = "Hello world!"
}

fun main() {
	app.run()
}
```

To use WebFlux.fn instead

 * Use `WebApplicationType.REACTIVE` instead of `WebApplicationType.SERVLET`
 * Use `webFlux { }` instead of `webMvc { }`
 * Use `spring-boot-starter-webflux` starter instead of `spring-boot-starter-web`
 * Use `coRouter { }` instead of `router { }` if you want to use Coroutines instead of Reactor API

== Dependencies

Kofu is technically just a dependency you add to your Spring Boot project.

```kotlin
dependencies {
	implementation("org.springframework.fu:spring-fu-kofu:0.2")

	implementation("org.springframework.boot:spring-boot-starter-web")
	testImplementation("org.springframework.boot:spring-boot-starter-webflux")
}
```

== Getting started

* Go to https://start.spring.io/#!type=gradle-project&language=kotlin[start.spring.io]
* Select latest Spring Boot `2.2.0.x` release
* Select the "Web" or "Reactive web" starter
* Add the `org.springframework.fu:spring-fu-kofu:{spring-fu-version}` dependency
* Modify the generated `DemoApplication.kt` file as following:

```kotlin
package com.sample

import org.springframework.fu.kofu.application

val app = application(...) {
	...
}

fun main() {
	app.run()
}
```

See sample projects https://github.com/spring-projects/spring-fu/tree/master/samples[here].

You can now also benefits of
https://docs.spring.io/spring/docs/current/spring-framework-reference/[Spring Framework reference documentation]
which is now available with Kotlin code samples.

== Credits

In addition to the whole Spring and Reactor teams, special credits to:

 * https://github.com/jhoeller[Juergen Hoeller] for his support on Kotlin and the functional bean registration API
 * https://github.com/poutsma[Arjen Poutsma] for creating the WebFlux functional API
 * https://github.com/tgirard12[Thomas Girard] for its https://github.com/tgirard12/spring-webflux-kotlin-dsl[spring-webflux-kotlin-dsl] experiment that initially demonstrated this approach was possible
 * https://github.com/konrad-kaminski[Konrad Kaminski] for his awesome https://github.com/konrad-kaminski/spring-kotlin-coroutine[spring-kotlin-coroutine] project
 * https://github.com/dsyer[Dave Syer] for his work on benchmarks, GraalVM support and functional bean registration applied to Boot
 * The whole https://github.com/spring-projects/spring-boot[Spring Boot] team
