image:https://ci.spring.io/api/v1/teams/spring-fu/pipelines/spring-fu/badge["Build Status", link="https://ci.spring.io/teams/spring-fu/pipelines/spring-fu"]

Spring Fu is an incubator for https://github.com/spring-projects-experimental/spring-fu/tree/master/jafu[JaFu] (Java DSL)
and https://github.com/spring-projects-experimental/spring-fu/tree/master/kofu[KoFu] (Kotlin DSL) designed to configure
Spring Boot explicitly with code in a declarative way with great  discoverability thanks to auto-complete.
It provides fast startup (40% faster than regular auto-configuration on a minimal Spring MVC app), low memory consumption
and is a good fit with https://www.graalvm.org/docs/reference-manual/native-image/[GraalVM native] thanks to its (almost) reflection-less approach.

== Native images

If you are interested in running Spring applications (including JaFu and KoFu ones) as GraalVM native images,
see the https://github.com/spring-projects-experimental/spring-graalvm-native[spring-graalvm-native] project and its https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-samples/jafu[jafu] and https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-samples/jafu-webmvc[jafu-webmvc] samples.

== Status

Spring Fu is not intended to be used in production yet, but rather to incubate and get feedback and contributions
from the community in order to hopefully reach a point where it can be integrated as part of Spring Framework and Spring
Boot.

== Credits

In addition to the whole Spring and Reactor teams, special credits to:

 * https://github.com/jhoeller[Juergen Hoeller] for his support on Kotlin and the functional bean registration API
 * https://github.com/poutsma[Arjen Poutsma] for creating the WebFlux functional API
 * https://github.com/tgirard12[Thomas Girard] for its https://github.com/tgirard12/spring-webflux-kotlin-dsl[spring-webflux-kotlin-dsl] experiment that initially demonstrated this approach was possible
 * https://github.com/konrad-kaminski[Konrad Kaminski] for his awesome https://github.com/konrad-kaminski/spring-kotlin-coroutine[spring-kotlin-coroutine] project
 * https://github.com/dsyer[Dave Syer] for his work on benchmarks, GraalVM support and functional bean registration applied to Boot
 * The whole https://github.com/spring-projects/spring-boot[Spring Boot] team
