:spring-fu-version: 0.0.5
:kofu-kdoc-url: http://repo.spring.io/milestone/org/springframework/fu/spring-fu-kofu/{spring-fu-version}/spring-fu-kofu-{spring-fu-version}-javadoc.jar!
:framework-kdoc-url: https://docs.spring.io/spring-framework/docs/5.2.0.BUILD-SNAPSHOT/kdoc-api

= Spring Fu

image::https://ci.spring.io/api/v1/teams/spring-fu/pipelines/spring-fu/badge["Build Status", link="https://ci.spring.io/teams/spring-fu/pipelines/spring-fu"]

Spring Fu is an incubator for features related to https://kotlinlang.org/[Kotlin], explicit configuration and runtime efficiency.

Its main incubating feature is *Kofu*, which provides any API to configure Spring Boot applications in an explicit way. Instead of leveraging auto-configuration and annotations, Kofu provides a nice `application { }` DSL to configure Spring Boot explicitly and efficiently with great discoverability via auto-complete in the IDE.

It has following characteristics:

 * Explicit configuration via Kotlin or Java DSL instead of annotations
 * Minimal set of features enabled by default
 * No classpath scanning, no feature enabled based on classpath detection
 * Both declarative (via the DSL) and programmatic (code auto-complete, allow any kind of `if`, `for` statements)
 * Functional configuration based on pure lambdas
 * Minimal reflection usage, no CGLIB proxy, no annotation processing
 * Fast startup and low memory consumption
 * https://github.com/oracle/graal/tree/master/substratevm[GraalVM native image] friendly
 * Lazy loading of beans enabled by default

It is not intended to be used in production, but rather to incubate and get feedback and contributions
from the community in order to reach a point where its features can be integrated as part of existing
Spring projects like Framework, Boot and Data.

== API reference

An overview of Kofu DSL is provided bellow with the related {kofu-kdoc-url}/kofu/index.html[API documentation].

```kotlin
val dataConfig = configuration { <1>
	beans { } <2>
	mongodb { } <3>
	r2dbcH2 { } <4>
	r2dbcPostgresql {} <5>
}

val webConfig = configuration { <1>
	beans { } <2>
	webFlux { <6>
		engine = <7>
		port = <8>
		router { } <9>
		include() <10>
		coRouter { } <11>
		cors { } <12>
		codecs { } <13>
		mustache() <14>
		filter() <15>
	}
	webClient { <16>
		baseUrl = <17>
		codecs { } <18>
	}
}

val app = application(WebApplicationType.REACTIVE) { <19>
	logging { } <20>
	configurationProperties<SampleProperties>() <21>
	listener<SampleEvent> { } <22>
	profile("sample"){ } <23>
	enable(dataConfig) <24>
	enable(webConfig) <24>
}

fun main() {
	app.run() <25>
}
```
 * 1 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-configuration-dsl/index.html[configuration documentation]
 ** 2 {framework-kdoc-url}/spring-framework/org.springframework.context.support/-bean-definition-dsl/index.html[beans documentation]
 ** 3 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.mongo/-mongo-dsl/index.html[mongo documentation]
 ** 4 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.r2dbc/r2dbc-h2.html[r2dbc-h2 documentation]
 ** 5 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.r2dbc/r2dbc-postgresql.html[r2dbc-postgresql documentation]
 * 6 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-server-dsl/index.html[WebFlux server documentation]
 ** 7 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-server-dsl/engine.html[engine documentation]
 ** 8 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-server-dsl/port.html[port documentation]
 ** 9 {framework-kdoc-url}/spring-framework/org.springframework.web.reactive.function.server/-router-function-dsl/index.html[router documentation]
 ** 10 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-server-dsl/co-router.html[Coroutines router documentation]
 ** 11 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-server-dsl/include.html[Include router documentation]
 ** 12 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/cors.html[cors documentation]
 ** 13 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-server-dsl/-web-flux-server-codec-dsl/index.html[codecs documentation]
 ** 14 {kofu-kdoc-url}/kofu/build/dokka/kofu/org.springframework.fu.kofu.webflux/mustache.html[mustache documentation]
 ** 15 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-server-dsl/filter.html[filter documentation]
 * 16 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-client-dsl/index.html[WebFlux client documentation]
 ** 17 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-client-dsl/base-url.html[baseUrl documentation]
 ** 18 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-client-dsl/-web-flux-client-codec-dsl/index.html[codecs documentation]
 * 19 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-application-dsl/index.html[application/application documentation]
 ** 20 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-logging-dsl/index.html[logging documentation]
 ** 21 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-configuration-dsl/configuration-properties.html[configuration-properties documentation]
 ** 22 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-configuration-dsl/listener.html[listener-properties documentation]
 ** 23 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-configuration-dsl/profile.html[profile-properties documentation]
 ** 24 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-configuration-dsl/enable.html[enable documentation]
 ** 25 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-kofu-application/run.html[run documentation]

== Getting started

* Create a Spring `2.2.x` project on https://start.spring.io/#!language=kotlin[start.spring.io] with the "Reactive web" starter
* Add the Spring milestone repository `https://repo.spring.io/milestone`
* Add the `org.springframework.fu:spring-fu-kofu:{spring-fu-version}` dependency
* Use latest Kotlin `1.3.x`
* Modify the generated `DemoApplication.kt` file as following:

```kotlin
package com.sample

import org.springframework.fu.kofu.application

val app = application(WebApplicationType.REACTIVE) {
	webFlux {
		router {
			GET("/") { ok().syncBody("Hello world!") }
		}
	}
}

fun main() {
	app.run()
}
```

== Samples

=== kofu-reactive-minimal

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-reactive-minimal[Browse source] |
http://repo.spring.io/milestone/org/springframework/fu/spring-fu-samples-kofu-reactive-minimal/{spring-fu-version}/spring-fu-samples-kofu-reactive-minimal-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot Reactive web application with Kofu configuration which provides a
`http://localhost:8080/` endpoint that displays "Hello world!" and an `http://localhost:8080/api` with a JSON
endpoint.

You can run compile and run it as a https://github.com/oracle/graal/tree/master/substratevm[Graal native image]
(GraalVM 1.0 RC10+) by running `./build.sh` then `./com.sample.applicationkt`.

=== kofu-reactive-mongodb

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-reactive-mongodb[Browse source] |
http://repo.spring.io/milestone/org/springframework/fu/spring-fu-samples-kofu-reactive-mongodb/{spring-fu-version}/spring-fu-samples-kofu-reactive-mongodb-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot Reactive web application with Kofu configuration and a Reactive MongoDB backend.

=== kofu-reactive-r2dbc

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-reactive-r2dbc[Browse source] |
http://repo.spring.io/milestone/org/springframework/fu/spring-fu-samples-kofu-reactive-r2dbc/{spring-fu-version}/spring-fu-samples-kofu-reactive-r2dbc-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot Reactive web application with Kofu configuration and a R2DBC backend.

=== kofu-coroutines-mongodb

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-coroutines-mongodb[Browse source] |
http://repo.spring.io/milestone/org/springframework/fu/spring-fu-samples-kofu-coroutines-mongodb/{spring-fu-version}/spring-fu-samples-kofu-coroutines-mongodb-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot Coroutines web application with Kofu configuration and a Reactive MongoDB backend.

=== kofu-coroutines-r2dbc

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-coroutines-r2dbc[Browse source] |
http://repo.spring.io/milestone/org/springframework/fu/spring-fu-samples-kofu-coroutines-r2dbc/{spring-fu-version}/spring-fu-samples-kofu-coroutines-r2dbc-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot Coroutines web application with Kofu configuration and a R2DBC backend.

== Credits

In addition to the whole Spring and Reactor teams, special credits to:

 * https://github.com/jhoeller[Juergen Hoeller] for his support on Kotlin and the functional bean registration API
 * https://github.com/poutsma[Arjen Poutsma] for creating the WebFlux functional API
 * https://github.com/tgirard12[Thomas Girard] for its https://github.com/tgirard12/spring-webflux-kotlin-dsl[spring-webflux-kotlin-dsl] experiment that initially demonstrated this approach was possible
 * https://github.com/konrad-kaminski[Konrad Kaminski] for his awesome https://github.com/konrad-kaminski/spring-kotlin-coroutine[spring-kotlin-coroutine] project
 * https://github.com/dsyer[Dave Syer] for his work on benchmarks, GraalVM support and functional bean registration applied to Boot
 * The whole https://github.com/spring-projects/spring-boot[Spring Boot] team