= Spring Fu

image::https://ci.spring.io/api/v1/teams/spring-fu/pipelines/spring-fu/badge["Build Status", link="https://ci.spring.io/teams/spring-fu/pipelines/spring-fu"]

Spring Fu is an incubator for new Spring features about Kotlin and functional bean registration.
Its main feature is an alternative way of configuring Spring Boot applications with Kotlin DSL and lambdas instead of annotations:
Kofu (for **Ko**tlin and **fu**nctional) configuration. Other features like Coroutines or
GraalVM support are also included. A Java variant called Jafu (for **Ja**va and **fu**nctional) is also expected.

It is not intended to be used in production, but rather to incubate and get feedback and contributions
from the community in order to reach a point where its features can be integrated as part of existing
Spring projects like Framework, Boot and Data. The table bellow summarize the status of current features.

== Status

|=====
a|**Feature** |**Status** |**Related issue**
a|
<<kofu-configuration,Kofu configuration>>
a|
Incubating in Spring Fu
a|
https://github.com/spring-projects/spring-boot/issues/8115[spring-boot#8115]

a|
https://github.com/spring-projects/spring-fu/tree/master/coroutines/webflux[Coroutines WebFlux support]
a|
Incubating in Spring Fu
a|
https://jira.spring.io/browse/SPR-15413[SPR-15413]

a|
https://github.com/spring-projects/spring-fu/tree/master/coroutines/mongodb[Coroutines MongoDB support]
a|
Incubating in Spring Fu
a|
To be created in Spring Data issue tracker


a|
https://github.com/spring-projects/spring-fu/issues/14[Coroutines SQL support]
a|
Not started yet
a|
To be created in Spring Data issue tracker

a|
Data classes support for configuration properties
a|
Expected in Spring Boot 2.2 (to be confirmed)
a|
https://github.com/spring-projects/spring-boot/issues/8762[spring-boot#8762]

a|
https://github.com/spring-projects/spring-fu/issues/69[Lite Kotlin reflection support]
a|
Incubating in Spring Fu
a|
https://jira.spring.io/browse/SPR-17008[SPR-17008]


a|
https://github.com/spring-projects/spring-fu/issues/34[Spring classpath filtering via Gradle plugin]
a|
Not started yet
a|




a|
https://github.com/spring-projects/spring-fu/tree/master/samples/graal[GraalVM support]
a|
Initial support done in Spring Framework 5.1

Work in progress on GraalVM side
a|
https://jira.spring.io/browse/SPR-16991[SPR-16991]

https://github.com/spring-projects/spring-boot/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22theme%3A+graal%22+[spring-boot graal theme]

a|
https://github.com/spring-projects/spring-fu/issues/14[Gradle Kotlin DSL]
a|
Pull-request to be contributed
a|
https://github.com/spring-io/initializr/issues/334[initializr#334]

a|
Better Kotlin documentation
a|
Not started yet
a|
https://jira.spring.io/browse/SPR-17245[SPR-17245]

|=====

[[kofu-configuration]]
== Kofu configuration

Kofu (for **Ko**tlin and **fu**nctional) is an alternative way of configuring your Spring application,
different from regular auto-configuration. It is based on Spring Boot without auto-configuration enabled
and has following characteristics:

 * https://dzone.com/articles/kotlin-dsl-from-theory-to-practice[Kotlin DSL] instead of annotation
 ** Minimal set of features enabled by default
 ** Explicit configuration
 ** No classpath scanning
 ** No feature enabled based on classpath detection
 ** Both declarative (via the DSL) and programmatic (code auto-complete, allow any kind of `if`, `for` statements)
 * Functional configuration based on pure lambdas
 ** Minimal reflection usage
 ** No CGLIB proxy
 ** No annotation processing
 * Faster startup and lower memory consumption (see <<kofu-benchmarks,benchmarks>>)
 * https://github.com/oracle/graal/tree/master/substratevm[GraalVM native image] friendly


The `application { }` Kotlin DSL allows you to configure your application explicitly. Each custom
block like `configuration` or `server` is in fact a more high level `beans {}` block with a custom
DSL provided for easy configuration. Since this configuration is code, you can use any kind of
custom programmatic bean registration without having to implement your own `@Conditional` annotation.

Here is an example of a typical Spring Fu application functional configuration.
```kotlin
fun main(args: Array<String) = application {
	logging {
		level(INFO)
		level("org.springframework", DEBUG)
	}
	configuration<SampleConfiguration>("sample")
	profile("data") {
		beans {
			bean<UserRepository>()
			bean<ArticleRepository>()
		}
		mongodb(uri = "mongodb://myserver.com/foo")
		listener<ContextStartedEvent> {
			ref<UserRepository>().init()
			ref<ArticleRepository>().init()
		}
	}
	profile("web") {
		beans {
			bean<HtmlHandler>()
			bean<ApiHandler>()
		}
		val port = if (profiles.contains("test")) 8181 else 8080
		server(netty(port)) {
			cors(origin = "example.com")
			mustache()
			codecs {
				string()
				jackson()
			}
			include { routes(ref(), ref()) }
			security { // TODO }
		}
		client {
			codecs {
				string()
				jackson()
			}
		}

	}
}.run(profiles = "data, web")

fun routes(htmlHandler: HtmlHandler, apiHandler: ApiHandler) = router {
	GET("/", htmlHandler::blog)
	GET("/article/{id}", htmlHandler::article)
	"/api".nest {
		GET("/", apiHandler::list)
		POST("/", apiHandler::create)
		PUT("/{id}", apiHandler::update)
		DELETE("/{id}", apiHandler::delete)
	}
}
```

See this https://github.com/spring-projects/spring-fu/blob/master/kofuconfig-javaconfig.adoc[Kofu versus Javaconfig comparison] for more details.

[[kofu-benchmarks]]
=== Startup time and memory benchmarks

Benchmarks done on a Dell Precision 5520, i7-7820HQ 2.90 GHz, 32G memory, Ubuntu 18.04 with Spring Boot 2.1 M2 on Java 8.0.172-zulu.

On basic projects, Kofu configuration is significantly faster and consume less memory than
auto-configuration. This is not surprising since Kofu configuration is by design explicit, minimal,
involve fewer conditions, has missing features and is based on lambdas instead of CGLIB proxies.

Relative startup time difference may be less important with bigger projects, to be validated with a
Kofu version of https://github.com/mixitconf/mixit[MiXiT web application].

==== Kofu configuration

Reactive webapp without Jackson without kotlin-reflect:

 * started application in 0.368 seconds (JVM running for 0.638)
 * Used PSYoungGen  21071K
 * Used ParOldGen      8K
 * Used Metaspace   17059K

Reactive webapp with Jackson without kotlin-reflect:

 * started application in 0.516 seconds (JVM running for 0.779)
 * Used PSYoungGen  41826K
 * Used ParOldGen      16K
 * Used Metaspace   19636K

Reactive webapp with Jackson with kotlin-reflect:

 * started application in 0.808 seconds (JVM running for 1.13)
 * Used PSYoungGen  61169K
 * Used ParOldGen    7029K
 * Used Metaspace   23357K

==== Auto configuration

Reactive webapp without Jackson without kotlin-reflect:

 * started application in 1.14 seconds (JVM running for 1.492)
 * Used PSYoungGen  107083K
 * Used ParOldGen     8270K
 * Used Metaspace    25723K

Reactive webapp with Jackson without kotlin-reflect:

 * started application in 1.133 seconds (JVM running for 1.48)
 * Used PSYoungGen  140088K
 * Used ParOldGen    7233K
 * Used Metaspace   29280K

Reactive webapp with Jackson with kotlin-reflect:

 * started application in 1.204 seconds (JVM running for 1.564)
 * Used PSYoungGen  202924K
 * Used ParOldGen     5776K
 * Used Metaspace    31791K

=== Beans

Beans are simply defined as follows.

```kotlin
application {
	beans {
		bean<UserRepository>()
		bean<ArticleRepository>()
		bean<HtmlHandler>()
		bean<ApiHandler>()
	}
}

```

Since classes with a single constructor have their parameters automatically autowired, it is recommended
to use constructor injection with `val` read-only (and non-nullable when possible) private
https://kotlinlang.org/docs/reference/properties.html[properties].

[source,kotlin]
----
class HtmlHandler(
	private val userRepository: UserRepository,
	private val articleRepository: ArticleRepository
) {
	// ...
}
----

=== Logging

Logging configuration can be done as following:

```kotlin
application {
	logging {
		level(INFO)
		level("org.springframework", DEBUG)
		level<DefaultListableBeanFactory>(WARN)
	}
}
```

=== Configuration properties

Configuration properties mechanism is the same than regular
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-typesafe-configuration-properties[Spring Boot configuration properties mechanism],
without the need to use `@ConfigurationProperties` annotation:

```kotlin
application {
	configuration<SampleConfiguration>(prefix = "sample")
}

// TODO Switch to data classes when https://github.com/spring-projects/spring-boot/issues/8762 will be fixed
class SampleConfiguration {
	lateinit var message: String
}
```

Configure your application with following `application.properties` file:
```
sample.message=hello
```

And that's it, you can now inject `SampleConfiguration` where you need.

=== Listeners

Declare application event Listeners in order to run tasks when `ApplicationContextEvent` like
`ApplicationReadyEvent` are emitted.

```kotlin
application {
	listener<ApplicationContextEvent> {
		ref<UserRepository>().init()
	}
}
```

=== WebFlux

Require `org.springframework.boot:spring-boot-starter-webflux` dependency.

This DSL configures https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#spring-webflux[WebFlux] client or server. 0..n clients are supported (you can specify the bean name to differentiate them) while only 0..1 server can ben declared. If multiple servers are needed, create one application per server (as usual in microservices architecture).

When no codec is configured, `String` and `Resource` ones are configured by default.
When a `codecs { }` block is declared, no one is configured by default.

==== Server

```kotlin
application {
	beans {
		bean<HtmlHandler>()
		bean<ApiHandler>()
	}
	server(netty()) {
		codecs {
			string()
			jackson()
		}
		router {
			val htmlHandler = ref<HtmlHandler>()
			val apiHandler = ref<ApiHandler>()
			GET("/", htmlHandler::blog)
			GET("/article/{id}", htmlHandler::article)
			"/api".nest {
				GET("/", apiHandler::list)
				POST("/", apiHandler::create)
				PUT("/{id}", apiHandler::update)
				DELETE("/{id}", apiHandler::delete)
			}
		}
	}
	client {
		codecs {
			string()
			jackson()
		}
	}
}
```

==== Client

```kotlin
application {
	client {
		codecs {
			string()
			jackson()
		}
	}
}
```

==== Coroutines

Require `org.springframework.fu:spring-boot-starter-webflux-coroutines` dependency.

This DSL adds support for WebFlux Coroutine API and can create a `CoroutinesWebClient` bean.

```kotlin
application {
	beans {
		bean<CoroutineHandler>()
	}
	server(netty()) {
		codecs {
			jackson()
		}
		coRouter {
			val coroutinesHandler = ref<CoroutinesHandler>()
			GET("/", coroutinesHandler::blog)
			GET("/article/{id}", coroutinesHandler::article)
		}
	}
	client {
		coroutines()
		codecs {
			jackson()
		}
	}
}
```

==== Cors

```kotlin
application {
	server(netty()) {
		cors {
			"/api" {
				allowedOrigins("first.example.com", "second.example.com")
				allowedMethods("GET", "PUT", "POST", "DELETE")
			}
			"/public" {
				allowedOrigins("**")
				allowedMethods("GET")
			}
			"/fullConfig" {
				allowedOrigins("full.config.example.com")
				allowedMethods("GET")
				allowedHeaders("*")
				exposedHeaders("Content-Location")
				allowCredentials = true
				maxAge = 3600
				defaults = false
			}
		}
	}
}
```

==== Mustache

Require `org.springframework.boot:spring-boot-starter-mustache` dependency.

This DSL configures a https://github.com/samskivert/jmustache[Mustache] view resolver.

```kotlin
application {
	server(netty()) {
		mustache()
	}
}
```

==== Jackson

Require `org.springframework.boot:spring-boot-starter-json` dependency (included by default in
`spring-boot-starter-webflux`).

This DSL configures a https://github.com/FasterXML/jackson[Jackson] JSON codec on WebFlux server
and client.

```kotlin
application {
	server(netty()) {
		codecs {
			jackson()
		}
	}
	client {
		codecs {
			jackson()
		}
	}
}
```

=== MongoDB

==== Reactive

Require `org.springframework.boot:spring-boot-starter-data-mongodb-reactive` dependency.

This DSL configures a `ReactiveMongoTemplate` bean.

```kotlin
application {
	mongodb("mongodb://myserver.com/foo")
}
```

==== Coroutines

Require `org.springframework.fu:spring-boot-starter-webflux-coroutines` dependency.

This DSL configures a `CoroutinesMongoTemplate` bean.

```kotlin
application {
	mongodb("mongodb://myserver.com/foo") {
		coroutines()
	}
}
```

==== Embedded

Require `de.flapdoodle.embed:de.flapdoodle.embed.mongo` dependency.

This DSL configures and runs a embedded MongoDB.

```kotlin
application {
	mongodb("mongodb://myserver.com/foo") {
	    embedded()
	}
}
```

== Getting started

=== Via start.spring.io

 * Create a Spring 2.1.0.BUILD-SNAPSHOT project on https://start.spring.io/[start.spring.io],
 * Add the `org.springframework.fu:spring-boot-kofu:0.0.1.BUILD-SNAPSHOT` dependency
 * Use Kotlin `1.3-M2` available from `http://dl.bintray.com/kotlin/kotlin-eap` Maven repository.
 * Modify the generated `*Application.kt` file as following:

```kotlin
package com.example

import org.springframework.fu.kofu.application

val app = application {
	// ...
}

fun main(args: Array<String>) = app.run()
```

=== Via bootstraps

Bootstraps are zip archives containing minimal project templates designed to allow you getting started
quickly and easily Spring Fu applications using a Gradle DSL build. To start a new project, download
a bootstrap `.zip` archive, extract it and follow `README.adoc` instructions.

 * https://repo.spring.io/libs-snapshot-local/org/springframework/fu/spring-fu-bootstrap-reactive/0.0.1.BUILD-SNAPSHOT/spring-fu-bootstrap-reactive-0.0.1.BUILD-SNAPSHOT.zip[spring-fu-bootstrap-reactive.zip]
 * https://repo.spring.io/libs-snapshot-local/org/springframework/fu/spring-fu-bootstrap-coroutines/0.0.1.BUILD-SNAPSHOT/spring-fu-bootstrap-coroutines-0.0.1.BUILD-SNAPSHOT.zip[spring-fu-bootstrap-coroutines.zip]

=== Samples

You can have a look to the sample applications:

* https://github.com/spring-projects/spring-fu/tree/master/samples/reactive[Reactive webapp]
* https://github.com/spring-projects/spring-fu/tree/master/samples/coroutines[Coroutine webapp]
* https://github.com/spring-projects/spring-fu/tree/master/samples/graal[Graal native image webapp]

=== Credits

In addition to the whole Spring and Reactor teams, special credits to:

 * https://github.com/jhoeller[Juergen Hoeller] for his support on Kotlin and the functional bean registration API
 * https://github.com/poutsma[Arjen Poutsma] for creating the WebFlux functional API
 * https://github.com/tgirard12[Thomas Girard] for its https://github.com/tgirard12/spring-webflux-kotlin-dsl[spring-webflux-kotlin-dsl] experiment that initially demonstrated this approach was possible
 * https://github.com/konrad-kaminski[Konrad Kaminski] for his awesome https://github.com/konrad-kaminski/spring-kotlin-coroutine[spring-kotlin-coroutine] project
