image::https://ci.spring.io/api/v1/teams/spring-fu/pipelines/spring-fu/badge["Build Status", link="https://ci.spring.io/teams/spring-fu/pipelines/spring-fu"]

Spring Fu (for **fu**nctional APIs) is an experimental https://kotlinlang.org/[Kotlin] micro-framework based on functional configuration intended to test ideas for upcoming https://spring.io/projects/spring-boot[Spring Boot] releases. It makes it easy to create fast and lightweight https://spring.io/projects/spring-framework[Spring]-powered applications with <<functional-configuration,functional APIs>> instead of annotations.

See the https://repo.spring.io/snapshot/org/springframework/fu/spring-fu-reference/0.0.1.BUILD-SNAPSHOT/spring-fu-reference-0.0.1.BUILD-SNAPSHOT.html[reference documentation] for more details.

== Overview

A simple Spring Fu web application rendering an HTML page and exposing a JSON HTTP endpoint looks like that:

```kotlin
fun main(args: Array<String>) = application {
	beans {
		bean<UserRepository>()
		bean<UserHandler>()
	}
	val port = if (profiles.contains("test")) 8181 else 8080
	server(netty(port)) {
		mustache()
		codecs {
			jackson()
		}
		router {
			val userHandler = ref<UserHandler>()
			GET("/", userHandler::listView)
			GET("/api/user", userHandler::listApi)
		}
	}
}.run()
```

It leverages a subset of Spring https://github.com/spring-projects/spring-fu/issues?q=is%3Aissue+label%3Aspring-framework[Framework], https://github.com/spring-projects/spring-fu/issues?q=is%3Aissue+label%3A%22spring+boot%22[Boot], https://github.com/spring-projects/spring-fu/issues?q=is%3Aissue+is%3Aopen+label%3Aspring-data[ Data] and Security to provide an alternative configuration model for developing applications in Kotlin:

* Provides a Kotlin idiomatic developer experience
* Functional configuration via https://dzone.com/articles/kotlin-dsl-from-theory-to-practice[Kotlin DSL] instead of annotations
* Minimal reflection usage, no classpath scanning, no annotation processing required
* Explicit configuration: minimal core, no conventions, no classpath detection
* Flexible programmatic configuration: https://kotlinlang.org/docs/reference/control-flow.html[control flow] like `if`, or `for` can be used to register conditionally your beans
* Run as native image with instant startup via https://github.com/spring-projects/spring-fu/issues/29[GraalVM support]
* https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md[Coroutines] allow to leverage Spring Reactive support (WebFlux, Data) with imperative programming style
* https://github.com/spring-projects/spring-fu/issues/34[Spring packages filtering] in order to have a minimal classpath and deploy just what you need
* Optional https://github.com/spring-projects/spring-fu/issues/23[single language fullstack support] with frontend written in Kotlin (compile to JavaScript or https://webassembly.org/[WebAssembly])
* https://github.com/spring-projects/spring-fu/issues/14[Reactive/Coroutines SQL support]
* Self-sufficient opinionated documentation (Kotlin, constructor injection, functional configuration, WebFlux, Coroutines, etc.)

Please send us your feedback on the `#spring` channel of http://slack.kotlinlang.org/[Kotlin Slack]. Feel free to open issues, https://github.com/spring-projects/spring-fu/blob/master/CONTRIBUTING.adoc[contribute] fixes or new modules via pull requests.

== Getting started

Spring Fu https://github.com/spring-projects/spring-fu/milestone/1[`0.0.1`] is currently under active development so no release is available yet, but you have can try https://repo.spring.io/snapshot/org/springframework/fu/[`0.0.1.BUILD-SNAPSHOT` builds].

=== Bootstrap

A Spring Fu bootstrap is an archive containing minimal project templates designed to allow you getting started quickly and easily Spring Fu applications. To start a new project, download a bootstrap `.zip` archive, extract it and follow `README.adoc` instructions.

 * https://repo.spring.io/libs-snapshot-local/org/springframework/fu/reactive-bootstrap/0.0.1.BUILD-SNAPSHOT/reactive-bootstrap-0.0.1.BUILD-SNAPSHOT.zip[reactive-bootstrap.zip]
 * https://repo.spring.io/libs-snapshot-local/org/springframework/fu/coroutine-bootstrap/0.0.1.BUILD-SNAPSHOT/coroutine-bootstrap-0.0.1.BUILD-SNAPSHOT.zip[coroutine-bootstrap.zip]


=== Documentation

To start with Spring Fu, you can read the https://repo.spring.io/snapshot/org/springframework/fu/spring-fu-reference/0.0.1.BUILD-SNAPSHOT/spring-fu-reference-0.0.1.BUILD-SNAPSHOT.html[**reference documentation**].

API documentation will be available https://github.com/spring-projects/spring-fu/issues/8[shortly].

You can have a look to the sample applications:

* https://github.com/spring-projects/spring-fu/tree/master/samples/reactive-webapp[Reactive webapp]
* https://github.com/spring-projects/spring-fu/tree/master/samples/coroutine-webapp[Coroutine webapp]
* https://github.com/spring-projects/spring-fu/tree/master/samples/graal-webapp[Graal native image webapp]

=== Credits

In addition to the whole Spring and Reactor teams, special credits to:

 * https://github.com/jhoeller[Juergen Hoeller] for his support on Kotlin and the functional bean registration API
 * https://github.com/poutsma[Arjen Poutsma] for creating the WebFlux functional API
 * https://github.com/tgirard12[Thomas Girard] for its https://github.com/tgirard12/spring-webflux-kotlin-dsl[spring-webflux-kotlin-dsl] experiment that initially demonstrated this approach was possible
 * https://github.com/konrad-kaminski[Konrad Kaminski] for his awesome https://github.com/konrad-kaminski/spring-kotlin-coroutine[spring-kotlin-coroutine] project
