Spring Fu makes it easy to create https://spring.io/projects/spring-framework[Spring]-powered applications, micro-services and functions (Serverless) in https://kotlinlang.org/[Kotlin]. It is to Kotlin and functional programming what http://projects.spring.io/spring-boot/[Spring Boot] is to Java and annotations.

It is designed to be simple, fast and lightweight with minimal reflection thanks to https://spring.io/blog/2017/08/01/spring-framework-5-kotlin-apis-the-functional-way[Spring functional configuration] mechanism which makes it possible to do efficient dead code removal and should provide https://github.com/oracle/graal[Graalvm] native image support by creating beans using lambda and class references in Kotlin. A simple Spring Fu web application start in less than a second on modern hardware, consume only 16M of heap memory, and self-executable shrinked JAR is less than 10M.

A minimal core is enabled by default and configuration is always explicit. Spring Fu https://github.com/sdeleuze/spring-fu/tree/master/modules[modules] provide integration for various JVM technologies by providing required dependencies and functional configuration.

It also leverages https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#spring-webflux[Spring WebFlux] and Spring Data Reactive support to allow developing scalable applications, and give the choice to use powerful https://projectreactor.io/[Reactor] `Flux` and `Mono` API for functional programming or Kotlin https://kotlinlang.org/docs/reference/coroutines.html[Coroutines] for imperative programming. Functional actuators provides `health`, `beans`, `metrics`, `mapping` predefined endpoints.

Developer experience is efficient without requiring specific support since no annotation processing is involved. Custom configuration with full autocomplete is supported via Kotlin scripts (`*.kts` files).

Spring Fu will be also a good fit for Function as a Service (Serverless) thanks to its fast startup-time and to the fact it will take advantage of Kotlin first-class functional supports (top level functions, function types).

== Functional configuration

Here is an example of Spring Fu functional configuration.

```kotlin
data class AppConfiguration(
	val name: String
)

val app = application {
	profile("data") {
		beans {
			bean<UserRepository>()
			bean<ArticleRepository>()
		}
		mongodb(uri = "mongodb://myserver.com/foo")
	}
	profile("web") {
		beans {
			bean<HtmlHandler>()
			bean<ApiHandler>()
		}
		webflux {
			val htmlHandler = ref<HtmlHandler>()
			val apiHandler = ref<ApiHandler>()
			server(engine = NETTY) {
				cors(origin = "example.com")
				mustache()
				codecs {
					jackson()
					protobuf()
				}
				routes {
					GET("/", htmlHandler::blog)
					GET("/article/{id}", htmlHandler:article)
					"/api".nest {
						GET("/", apiHandler::list)
						POST("/", apiHandler::create)
						PUT("/{id}", apiHandler::update)
						DELETE("/{id}", apiHandler::delete)
					}
				}
				security {
					// ...
				}
			}
			client(engine = JETTY) {
				codecs {
					jackson()
				}
			}
		}
	}
	configuration {
	    AppConfiguration(name = env["SYSTEM_ENV"] ?: "default")
	}
}

fun main(args: Array<String) {
	app.run()
}
```

== Reference documentation

* https://github.com/sdeleuze/spring-fu/tree/master/core[Core]
* Modules
** https://github.com/sdeleuze/spring-fu/tree/master/modules/dynamic-configuration[Dynamic configuration]
** https://github.com/sdeleuze/spring-fu/tree/master/modules/jackson[Jackson]
** https://github.com/sdeleuze/spring-fu/tree/master/modules/mongodb[MongoDB]
** https://github.com/sdeleuze/spring-fu/tree/master/modules/mustache[Mustache]
** https://github.com/sdeleuze/spring-fu/tree/master/modules/test[Test]
** https://github.com/sdeleuze/spring-fu/tree/master/modules/webflux[WebFlux]

== Samples

* https://github.com/sdeleuze/spring-fu/tree/master/samples/simple-webapp[Simple webapp]

== Credits

Kudos to https://github.com/tgirard12[Thomas Girard] for its https://github.com/tgirard12/spring-webflux-kotlin-dsl[spring-webflux-kotlin-dsl] experiment that initially demonstrated this approach was possible.