:spring-fu-version: 0.1.BUILD-SNAPSHOT
:kofu-kdoc-url: http://repo.spring.io/snapshot/org/springframework/fu/spring-fu-kofu/{spring-fu-version}/spring-fu-kofu-{spring-fu-version}-javadoc.jar!
:framework-kdoc-url: https://docs.spring.io/spring-framework/docs/5.2.0.BUILD-SNAPSHOT/kdoc-api

image::https://ci.spring.io/api/v1/teams/spring-fu/pipelines/spring-fu/badge["Build Status", link="https://ci.spring.io/teams/spring-fu/pipelines/spring-fu"]

= Kofu configuration for Spring Boot

Spring Fu is an incubator for *Kofu* (*Ko* for Kotlin, *fu* for functional), which provides any API to configure Spring Boot applications programmatically with following characteristics:

 * Explicit configuration via a Kotlin DSL instead of auto-configuration
 * Leverages Spring Framework 5.x https://docs.spring.io/spring/docs/5.2.0.BUILD-SNAPSHOT/spring-framework-reference/languages.html#kotlin-bean-definition-dsl[Functional bean configuration] instead of annotations
 * Allows to define custom configuration slices (useful for more focused and efficient testing)
 * Great discoverability via code auto-complete
 * https://docs.spring.io/spring/docs/5.2.0.BUILD-SNAPSHOT/spring-framework-reference/languages.html#router-dsl[Web functional routing] instead of `@Controller` available in 3 flavors:
 Expose the same Web functional routing programming model in 3 flavors:
 ** WebMvc.fn (functional variant Spring MVC)
 ** WebFlux.fn with Reactor declarative-style API (`Mono` and `Flux`)
 ** WebFlux.fn with Coroutines imperative-style API (https://spring.io/blog/2019/04/12/going-reactive-with-spring-coroutines-and-kotlin-flow[using suspending functions and Kotlin `Flow`])
 * Persistence via Spring Data functional APIs like:
 ** https://spring.io/projects/spring-data-r2dbc[Spring Data R2DBC `DatabaseClient`]
 ** Spring Data JDBC https://github.com/spring-projects/spring-data-jdbc/blob/master/spring-data-jdbc/src/main/java/org/springframework/data/jdbc/core/JdbcAggregateOperations.java[`JdbcAggregateOperations`]
 ** Spring Data NoSQL similar APIs for MongoDB, Redis and Cassandra
 * Configuration via Spring Security `security { }` DSL (WIP)
 * https://github.com/oracle/graal/tree/master/substratevm[GraalVM native image] friendly
 * Fast startup and low memory consumption

It is not intended to be used in production yet, but rather to incubate and get feedback and contributions
from the community in order to hopefully reach a point where it can be integrated as part of Spring Boot.

== Minimal application

Here is a minimal sample application that is leveraging WebMvc.fn:

```kotlin
val app = application(WebApplicationType.SERVLET) {
	beans {
		bean<SampleService>()
	}
	webMvc {
		port = if (profiles.contains("test")) 8181 else 8080
		router {
			val service = ref<SampleService>()
			GET("/") {
				ok().body(service.generateMessage())
			}
			GET("/api") {
				ok().body(Sample(service.generateMessage()))
			}
		}
	}
}

data class Sample(val message: String)

class SampleService {
	fun generateMessage() = "Hello world!"
}

fun main() {
	app.run()
}
```

To use WebFlux.fn instead

 * Use `WebApplicationType.REACTIVE` instead of `WebApplicationType.SERVLET`
 * Use `webFlux { }` instead of `webMvc { }`
 * Use `spring-boot-starter-webflux` starter instead of `spring-boot-starter-web`
 * Use `coRouter { }` instead of `router { }` if you want to use Coroutines instead of Reactor API

== Dependencies

Kofu is technically just a dependency you add to your Spring Boot project.

```kotlin
dependencies {
	implementation("org.springframework.fu:spring-fu-kofu:0.x")

	implementation("org.springframework.boot:spring-boot-starter-web")
	testImplementation("org.springframework.boot:spring-boot-starter-webflux")
}
```

== API reference

An overview of Kofu is provided bellow with the related {kofu-kdoc-url}/kofu/index.html[API documentation].

```kotlin
val dataConfig = configuration { <1>
	beans { } <2>
	mongodb { } <3>
	r2dbcH2 { } <4>
	r2dbcPostgresql {} <5>
}

val serverConfig = configuration { <1>
	beans { } <2>
	webFlux { <6>
		engine = <7>
		port = <8>
		router { } <9>
		include() <10>
		coRouter { } <11>
		cors { } <12>
		codecs { } <13>
		mustache() <14>
		filter() <15>
	}
}

val clientConfig = configuration {
	webClient { <16>
		baseUrl = <17>
		codecs { } <18>
	}
}

val app = application(WebApplicationType.REACTIVE) { <19>
	logging { } <20>
	configurationProperties<SampleProperties>() <21>
	listener<SampleEvent> { } <22>
	profile("sample"){ } <23>
	enable(dataConfig) <24>
	enable(serverConfig) <24>
	enable(clientConfig) <24>
}

fun main() {
	app.run() <25>
}
```
 * 1 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-configuration-dsl/index.html[configuration documentation]
 ** 2 {framework-kdoc-url}/spring-framework/org.springframework.context.support/-bean-definition-dsl/index.html[beans documentation]
 ** 3 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.mongo/-mongo-dsl/index.html[mongo documentation]
 ** 4 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.r2dbc/r2dbc-h2.html[r2dbc-h2 documentation]
 ** 5 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.r2dbc/r2dbc-postgresql.html[r2dbc-postgresql documentation]
 * 6 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-server-dsl/index.html[WebFlux server documentation]
 ** 7 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-server-dsl/engine.html[engine documentation]
 ** 8 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-server-dsl/port.html[port documentation]
 ** 9 {framework-kdoc-url}/spring-framework/org.springframework.web.reactive.function.server/-router-function-dsl/index.html[router documentation]
 ** 10 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-server-dsl/co-router.html[Coroutines router documentation]
 ** 11 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-server-dsl/include.html[Include router documentation]
 ** 12 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/cors.html[cors documentation]
 ** 13 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-server-dsl/-web-flux-server-codec-dsl/index.html[codecs documentation]
 ** 14 {kofu-kdoc-url}/kofu/build/dokka/kofu/org.springframework.fu.kofu.webflux/mustache.html[mustache documentation]
 ** 15 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-server-dsl/filter.html[filter documentation]
 * 16 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-client-dsl/index.html[WebFlux client documentation]
 ** 17 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-client-dsl/base-url.html[baseUrl documentation]
 ** 18 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.webflux/-web-flux-client-dsl/-web-flux-client-codec-dsl/index.html[codecs documentation]
 * 19 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-application-dsl/index.html[application/application documentation]
 ** 20 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-logging-dsl/index.html[logging documentation]
 ** 21 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-configuration-dsl/configuration-properties.html[configuration-properties documentation]
 ** 22 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-configuration-dsl/listener.html[listener-properties documentation]
 ** 23 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-configuration-dsl/profile.html[profile-properties documentation]
 ** 24 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-configuration-dsl/enable.html[enable documentation]
 ** 25 {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-kofu-application/run.html[run documentation]

== Getting started

* Create a Spring `2.2.0 (SNAPSHOT)` project on https://start.spring.io/#!language=kotlin[start.spring.io] with the "Web" or "Reactive web" starter
* Add the `org.springframework.fu:spring-fu-kofu:{spring-fu-version}` dependency
* Use latest Kotlin `1.3.x`
* Modify the generated `DemoApplication.kt` file as following:

```kotlin
package com.sample

import org.springframework.fu.kofu.application

val app = application(...) {
	...
}

fun main() {
	app.run()
}
```

== Samples

=== kofu-reactive-minimal

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-reactive-minimal[Browse source] |
http://repo.spring.io/snapshot/org/springframework/fu/spring-fu-samples-kofu-reactive-minimal/{spring-fu-version}/spring-fu-samples-kofu-reactive-minimal-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot Reactive web application with Kofu configuration which provides a
`http://localhost:8080/` endpoint that displays "Hello world!" and an `http://localhost:8080/api` with a JSON
endpoint.

You can run compile and run it as a https://github.com/oracle/graal/tree/master/substratevm[Graal native image]
(GraalVM 1.0 RC10+) by running `./build.sh` then `./com.sample.applicationkt`.

=== kofu-reactive-mongodb

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-reactive-mongodb[Browse source] |
http://repo.spring.io/snapshot/org/springframework/fu/spring-fu-samples-kofu-reactive-mongodb/{spring-fu-version}/spring-fu-samples-kofu-reactive-mongodb-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot Reactive web application with Kofu configuration and a Reactive MongoDB backend.

=== kofu-reactive-r2dbc

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-reactive-r2dbc[Browse source] |
http://repo.spring.io/snapshot/org/springframework/fu/spring-fu-samples-kofu-reactive-r2dbc/{spring-fu-version}/spring-fu-samples-kofu-reactive-r2dbc-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot Reactive web application with Kofu configuration and a R2DBC backend.

=== kofu-reactive-validation

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-reactive-validation[Browse source] |
http://repo.spring.io/milestone/org/springframework/fu/spring-fu-samples-kofu-reactive-validation/{spring-fu-version}/spring-fu-samples-kofu-reactive-validation-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot Reactive web application with Kofu configuration and validation using https://github.com/making/yavi[YAVI].

=== kofu-coroutines-mongodb

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-coroutines-mongodb[Browse source] |
http://repo.spring.io/snapshot/org/springframework/fu/spring-fu-samples-kofu-coroutines-mongodb/{spring-fu-version}/spring-fu-samples-kofu-coroutines-mongodb-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot Coroutines web application with Kofu configuration and a Reactive MongoDB backend.

=== kofu-coroutines-r2dbc

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-coroutines-r2dbc[Browse source] |
http://repo.spring.io/snapshot/org/springframework/fu/spring-fu-samples-kofu-coroutines-r2dbc/{spring-fu-version}/spring-fu-samples-kofu-coroutines-r2dbc-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot Coroutines web application with Kofu configuration and a R2DBC backend.

=== kofu-coroutines-validation

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-coroutines-validation[Browse source] |
http://repo.spring.io/milestone/org/springframework/fu/spring-fu-samples-kofu-coroutines-validation/{spring-fu-version}/spring-fu-samples-kofu-coroutines-validation-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot Coroutines web application with Kofu configuration and validation using https://github.com/making/yavi[YAVI].

=== kofu-servlet-minimal

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-servlet-minimal[Browse source] |
http://repo.spring.io/snapshot/org/springframework/fu/spring-fu-samples-kofu-servlet-minimal/{spring-fu-version}/spring-fu-samples-kofu-servlet-minimal-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot web application based on WebMvc.fn (functional variant of Spring MVC) with Kofu configuration which provides a
`http://localhost:8080/` endpoint that displays "Hello world!" and an `http://localhost:8080/api` with a JSON
endpoint.

== Credits

In addition to the whole Spring and Reactor teams, special credits to:

 * https://github.com/jhoeller[Juergen Hoeller] for his support on Kotlin and the functional bean registration API
 * https://github.com/poutsma[Arjen Poutsma] for creating the WebFlux functional API
 * https://github.com/tgirard12[Thomas Girard] for its https://github.com/tgirard12/spring-webflux-kotlin-dsl[spring-webflux-kotlin-dsl] experiment that initially demonstrated this approach was possible
 * https://github.com/konrad-kaminski[Konrad Kaminski] for his awesome https://github.com/konrad-kaminski/spring-kotlin-coroutine[spring-kotlin-coroutine] project
 * https://github.com/dsyer[Dave Syer] for his work on benchmarks, GraalVM support and functional bean registration applied to Boot
 * The whole https://github.com/spring-projects/spring-boot[Spring Boot] team
