== Roadmap

|=====
a|**Feature** |**Status** |**Related issue**

a|
https://github.com/spring-projects/spring-fu/tree/master/kofu[Kofu] and
https://github.com/spring-projects/spring-fu/tree/master/jafu[Jafu] configuration DSL
a|
Incubating in Spring Fu
a|
Slightly related: https://github.com/spring-projects/spring-boot/issues/8115[spring-boot#8115]
To be created in Spring Boot issue tracker

a|
More efficient Spring Boot startup via explicit configuration and https://github.com/spring-projects/spring-fu/tree/master/autoconfigure-adapter[functional bean registration]
a|
Manually created in Spring Fu

Experimented by https://github.com/dsyer[Dave Syer] in https://github.com/dsyer/spring-init-experiment[spring-init-experiment] and https://github.com/dsyer/spring-boot-micro-apps[spring-boot-micro-apps]

*Could* be generated during Spring Boot build in the future
a|
To be created in Spring Boot issue tracker

a|
https://github.com/spring-projects/spring-fu/tree/master/coroutines[Coroutines support]
a|
Incubating in Spring Fu
a|
https://jira.spring.io/browse/SPR-15413[SPR-15413]
https://github.com/Kotlin/kotlinx.coroutines/issues/254[kotlinx.coroutines#254]
https://github.com/Kotlin/kotlinx.coroutines/issues/284[kotlinx.coroutines#284]
To be created in Spring Data issue tracker for MongoDB and SQL support

a|
Data classes support for configuration properties
a|
Available in Spring Boot 2.2 snapshots
a|
https://github.com/spring-projects/spring-boot/issues/8762[spring-boot#8762]

a|
https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-reactive-minimal[GraalVM native images support]
a|
Initial support done in Spring Framework 5.1

Work in progress on GraalVM side
a|
https://jira.spring.io/browse/SPR-16991[SPR-16991]

https://github.com/spring-projects/spring-boot/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22theme%3A+graal%22+[spring-boot graal theme]

a|
Better Kotlin documentation
a|
Not started yet
a|
https://jira.spring.io/browse/SPR-17245[SPR-17245]

a|
https://github.com/spring-projects/spring-fu/issues/14[Gradle Kotlin DSL]
a|
Pull-request to be contributed
a|
https://github.com/spring-io/initializr/issues/334[initializr#334]

a|
https://github.com/spring-projects/spring-fu/issues/69[Lite Kotlin reflection support]
a|
Incubating in Spring Fu
a|
https://jira.spring.io/browse/SPR-17008[SPR-17008]

a|
https://github.com/spring-projects/spring-fu/issues/34[Spring classpath filtering via Gradle plugin]
a|
Not started yet
a|

a|
https://github.com/spring-projects/spring-fu/issues/85[Automated (and machine readable) HTTP API documentation]
a|
Not started yet
a|
https://github.com/spring-projects/spring-restdocs/issues/213[spring-restdocs#213]

|=====