= Kofu configuration

Kofu (for **Ko**tlin and **fu**nctional) is an alternative way of configuring your Spring Boot application,
different from regular auto-configuration. It is based on Spring Boot infrastructure, but used in a functional
way via lambdas instead of annotations
(see the https://github.com/spring-projects/spring-fu/tree/master/fuconfigure[fuconfigure] module).
It has following characteristics:

 * https://dzone.com/articles/kotlin-dsl-from-theory-to-practice[Kotlin DSL] instead of annotation
 ** Minimal set of features enabled by default
 ** Explicit configuration
 ** No classpath scanning
 ** No feature enabled based on classpath detection
 ** Both declarative (via the DSL) and programmatic (code auto-complete, allow any kind of `if`, `for` statements)
 * Functional configuration based on pure lambdas
 ** Minimal reflection usage
 ** No CGLIB proxy
 ** No annotation processing
 * Faster startup and lower memory consumption (see <<kofu-benchmarks,benchmarks>>)
 * https://github.com/oracle/graal/tree/master/substratevm[GraalVM native image] friendly


The `application { }` Kotlin DSL allows you to configure your application explicitly. Each custom
block like `configuration` or `server` is in fact a more high level `beans {}` block with a custom
DSL provided for easy configuration. Since this configuration is code, you can use any kind of
custom programmatic bean registration without having to implement your own `@Conditional` annotation.

Here is an example of a typical Spring Fu application functional configuration.
```kotlin
fun main(args: Array<String) = application {
	logging {
		level(INFO)
		level("org.springframework", DEBUG)
	}
	configuration<SampleConfiguration>("sample")
	profile("data") {
		beans {
			bean<UserRepository>()
			bean<ArticleRepository>()
		}
		mongodb(uri = "mongodb://myserver.com/foo")
		listener<ContextStartedEvent> {
			ref<UserRepository>().init()
			ref<ArticleRepository>().init()
		}
	}
	profile("web") {
		beans {
			bean<HtmlHandler>()
			bean<ApiHandler>()
		}
		val port = if (profiles.contains("test")) 8181 else 8080
		server(netty(port)) {
			cors(origin = "example.com")
			mustache()
			codecs {
				string()
				jackson()
			}
			include { routes(ref(), ref()) }
			security { // TODO }
		}
		client {
			codecs {
				string()
				jackson()
			}
		}

	}
}.run(profiles = "data, web")

fun routes(htmlHandler: HtmlHandler, apiHandler: ApiHandler) = router {
	GET("/", htmlHandler::blog)
	GET("/article/{id}", htmlHandler::article)
	"/api".nest {
		GET("/", apiHandler::list)
		POST("/", apiHandler::create)
		PUT("/{id}", apiHandler::update)
		DELETE("/{id}", apiHandler::delete)
	}
}
```


The dependency to use is `org.springframework.fu:spring-boot-kofu`.

== Beans

Beans are simply defined as follows.

```kotlin
application {
	beans {
		bean<UserRepository>()
		bean<ArticleRepository>()
		bean<HtmlHandler>()
		bean<ApiHandler>()
	}
}

```

Since classes with a single constructor have their parameters automatically autowired, it is recommended
to use constructor injection with `val` read-only (and non-nullable when possible) private
https://kotlinlang.org/docs/reference/properties.html[properties].

[source,kotlin]
----
class HtmlHandler(
	private val userRepository: UserRepository,
	private val articleRepository: ArticleRepository
) {
	// ...
}
----

== Logging

Logging configuration can be done as following:

```kotlin
application {
	logging {
		level(INFO)
		level("org.springframework", DEBUG)
		level<DefaultListableBeanFactory>(WARN)
	}
}
```

== Configuration properties

Configuration properties mechanism is the same than regular
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-typesafe-configuration-properties[Spring Boot configuration properties mechanism],
without the need to use `@ConfigurationProperties` annotation:

```kotlin
application {
	configuration<SampleConfiguration>(prefix = "sample")
}

// TODO Switch to data classes when https://github.com/spring-projects/spring-boot/issues/8762 will be fixed
class SampleConfiguration {
	lateinit var message: String
}
```

Configure your application with following `application.properties` file:
```
sample.message=hello
```

And that's it, you can now inject `SampleConfiguration` where you need.

== Listeners

Declare application event Listeners in order to run tasks when `ApplicationContextEvent` like
`ApplicationReadyEvent` are emitted.

```kotlin
application {
	listener<ApplicationContextEvent> {
		ref<UserRepository>().init()
	}
}
```

== WebFlux

Require `org.springframework.boot:spring-boot-starter-webflux` dependency.

This DSL configures https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#spring-webflux[WebFlux] client or server. 0..n clients are supported (you can specify the bean name to differentiate them) while only 0..1 server can ben declared. If multiple servers are needed, create one application per server (as usual in microservices architecture).

When no codec is configured, `String` and `Resource` ones are configured by default.
When a `codecs { }` block is declared, no one is configured by default.

=== Server

```kotlin
application {
	beans {
		bean<HtmlHandler>()
		bean<ApiHandler>()
	}
	server(netty()) {
		codecs {
			string()
			jackson()
		}
		router {
			val htmlHandler = ref<HtmlHandler>()
			val apiHandler = ref<ApiHandler>()
			GET("/", htmlHandler::blog)
			GET("/article/{id}", htmlHandler::article)
			"/api".nest {
				GET("/", apiHandler::list)
				POST("/", apiHandler::create)
				PUT("/{id}", apiHandler::update)
				DELETE("/{id}", apiHandler::delete)
			}
		}
	}
	client {
		codecs {
			string()
			jackson()
		}
	}
}
```

=== Client

```kotlin
application {
	client {
		codecs {
			string()
			jackson()
		}
	}
}
```

=== Coroutines

Require `org.springframework.fu:spring-boot-starter-webflux-coroutines` dependency.

This DSL adds support for WebFlux Coroutine API and can create a `CoroutinesWebClient` bean.

```kotlin
application {
	beans {
		bean<CoroutineHandler>()
	}
	server(netty()) {
		codecs {
			jackson()
		}
		coRouter {
			val coroutinesHandler = ref<CoroutinesHandler>()
			GET("/", coroutinesHandler::blog)
			GET("/article/{id}", coroutinesHandler::article)
		}
	}
	client {
		coroutines()
		codecs {
			jackson()
		}
	}
}
```

=== Cors

```kotlin
application {
	server(netty()) {
		cors {
			"/api" {
				allowedOrigins("first.example.com", "second.example.com")
				allowedMethods("GET", "PUT", "POST", "DELETE")
			}
			"/public" {
				allowedOrigins("**")
				allowedMethods("GET")
			}
			"/fullConfig" {
				allowedOrigins("full.config.example.com")
				allowedMethods("GET")
				allowedHeaders("*")
				exposedHeaders("Content-Location")
				allowCredentials = true
				maxAge = 3600
				defaults = false
			}
		}
	}
}
```

=== Mustache

Require `org.springframework.boot:spring-boot-starter-mustache` dependency.

This DSL configures a https://github.com/samskivert/jmustache[Mustache] view resolver.

```kotlin
application {
	server(netty()) {
		mustache()
	}
}
```

=== Jackson

Require `org.springframework.boot:spring-boot-starter-json` dependency (included by default in
`spring-boot-starter-webflux`).

This DSL configures a https://github.com/FasterXML/jackson[Jackson] JSON codec on WebFlux server
and client.

```kotlin
application {
	server(netty()) {
		codecs {
			jackson()
		}
	}
	client {
		codecs {
			jackson()
		}
	}
}
```

== MongoDB

=== Reactive

Require `org.springframework.boot:spring-boot-starter-data-mongodb-reactive` dependency.

This DSL configures a `ReactiveMongoTemplate` bean.

```kotlin
application {
	mongodb("mongodb://myserver.com/foo")
}
```

=== Coroutines

Require `org.springframework.fu:spring-boot-starter-webflux-coroutines` dependency.

This DSL configures a `CoroutinesMongoTemplate` bean.

```kotlin
application {
	mongodb("mongodb://myserver.com/foo") {
		coroutines()
	}
}
```

=== Embedded

Require `de.flapdoodle.embed:de.flapdoodle.embed.mongo` dependency.

This DSL configures and runs a embedded MongoDB.

```kotlin
application {
	mongodb("mongodb://myserver.com/foo") {
	    embedded()
	}
}
```

[[kofu-benchmarks]]
== Startup time and memory benchmarks

Benchmarks done on a Dell Precision 5520, i7-7820HQ 2.90 GHz, 32G memory, Ubuntu 18.04 with Spring Boot 2.1 M2 on Java 8.0.172-zulu.

On basic projects, Kofu configuration is significantly faster and consume less memory than
auto-configuration. This is not surprising since Kofu configuration is by design explicit, minimal,
involve fewer conditions, has missing features and is based on lambdas instead of CGLIB proxies.

Relative startup time difference may be less important with bigger projects, to be validated with a
Kofu version of https://github.com/mixitconf/mixit[MiXiT web application].

=== Kofu configuration

Reactive webapp without Jackson without kotlin-reflect:

 * started application in 0.368 seconds (JVM running for 0.638)
 * Used PSYoungGen  21071K
 * Used ParOldGen      8K
 * Used Metaspace   17059K

Reactive webapp with Jackson without kotlin-reflect:

 * started application in 0.516 seconds (JVM running for 0.779)
 * Used PSYoungGen  41826K
 * Used ParOldGen      16K
 * Used Metaspace   19636K

Reactive webapp with Jackson with kotlin-reflect:

 * started application in 0.808 seconds (JVM running for 1.13)
 * Used PSYoungGen  61169K
 * Used ParOldGen    7029K
 * Used Metaspace   23357K

=== Auto configuration

Reactive webapp without Jackson without kotlin-reflect:

 * started application in 1.14 seconds (JVM running for 1.492)
 * Used PSYoungGen  107083K
 * Used ParOldGen     8270K
 * Used Metaspace    25723K

Reactive webapp with Jackson without kotlin-reflect:

 * started application in 1.133 seconds (JVM running for 1.48)
 * Used PSYoungGen  140088K
 * Used ParOldGen    7233K
 * Used Metaspace   29280K

Reactive webapp with Jackson with kotlin-reflect:

 * started application in 1.204 seconds (JVM running for 1.564)
 * Used PSYoungGen  202924K
 * Used ParOldGen     5776K
 * Used Metaspace    31791K

== Comparison with annotation-based configuration

=== JavaConfig

Functional bean definition allows to define beans in an efficient way with minimal reflection usage, no proxy and with a concise Kotlin DSL that takes advantage of https://kotlinlang.org/docs/reference/inline-functions.html#reified-type-parameters[reified type parameters] to avoid type erasure. The `beans {}` block is in fact a regular https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/ApplicationContextInitializer.html[`ApplicationContextInitializer`].

|=====
a|**JavaConfig** |**Functional bean definition**
a|
```kotlin
 @Configuration
 class MyConfiguration {

  @Bean
  fun foo() = Foo()

  @Bean
  fun bar(foo: Foo) = Bar(foo)
}
```
a|
```kotlin
val myConfiguration = beans {
  bean<Foo>()
  // Implicit autowiring by constructor
  bean<Bar>()
}
|=====


==== Conditional registration

One key characteristic of functional bean definition is that you can
register bean programmatically using `if`, for `for` or other control flow where in
JavaConfig you rely on https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-auto-configuration.html#boot-features-bean-conditions[predefined or custom `@Conditional` annotations].

|=====
a|**JavaConfig** |**Functional bean definition**
a|
```kotlin
  class MyCustomCondition : Condition {

    override fun matches(context: c,
        m: AnnotatedTypeMetadata): Boolean {
      val myCustomLib = MyCustomLib()
      return myCustomLib.checkStatus()
    }
  }

  @Configuration
  class MyConfiguration {

    @Bean
    @Conditional(MyCustomCondition::class)
    fun foo() = Foo()
  }
```
a|
```kotlin
val testConfiguration = beans {

  val myCustomLib = MyCustomLib()
  if (myCustomLib.checkStatus()) {
    bean<Foo>()
  }
}
|=====


==== Profiles

A profiles shortcut (internally relying on programmatic bean registration) is provided in
functional bean definition.

|=====
a|**JavaConfig** |**Functional bean definition**
a|
```kotlin
 @Configuration
 @Profile("test")
 class TestConfiguration {

  @Bean
  fun foo() = Foo()

  @Bean
  fun bar(foo: Foo) = Bar(foo)
}
```
a|
```kotlin
val testConfiguration = beans {
  profile("test") {
    bean<Foo>()
    bean<Bar>()
  }
}
|=====

=== Component scanning

Functional bean definition is explicit, does not imply any classpath scanning and supports constructor parameters autowiring.

|=====
a|**`@Component` scanning** |**Functional bean definition**
a|
```kotlin
@Component
class Foo {
  // ...
}

@Component
class Bar(private val f: Foo) {
  // ...
}
```
a|
```kotlin
class Foo {
  // ...
}
class Bar(private val f: Foo) {
  // ...
}

beans {
  bean<Foo>()
  bean<Bar>()
}
|=====

=== Controllers

Kotlin WebFlux router provides a simple but powerful way to implement your web application. HTTP API, streaming but also view rendering are supported.

|=====
a|**Annotation-based controller** |**Kotlin WebFlux routes**
a|
```kotlin
@RestController
@RequestMapping("/api/article")
class MyController(private val r: MyRepository) {

  @GetMapping("/")
  fun findAll() =
    r.findAll()

  @GetMapping("/{id}")
  fun findOne(@PathVariable id: Long) =
    repository.findById(id)
  }
}
```
a|
```kotlin
router {
  val r = ref<MyRepository>()
  "/api/article".nest {
    GET("/") {
      r.findAll()
    }
    GET("/{id}") {
      val id = it.pathVariable("id")
      r.findById(id)
    }
  }
}
|=====
