:spring-fu-version: 0.0.3
:kofu-kdoc-url: http://repo.spring.io/milestone/org/springframework/fu/spring-fu-kofu/{spring-fu-version}/spring-fu-kofu-{spring-fu-version}-javadoc.jar!
:framework-kdoc-url: https://docs.spring.io/spring-framework/docs/5.1.x/kdoc-api
= Kofu DSL for Spring Boot

Kofu (for **Ko**tlin and **fu**nctional) is an alternative way of configuring explicitly your Spring Boot application,
different from regular auto-configuration, using a Kotlin DSL. It is based on Spring Boot infrastructure, but
https://github.com/spring-projects/spring-fu/tree/master/autoconfigure-adapter[used via functional bean definitions]
instead of JavaConfig.

== API reference

An overview of Kofu DSL is provided bellow with the related {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/index.html[API documentation].

```kotlin
val dataConf = configuration { <1>
	beans { } <2>
	mongodb { } <3>
	r2dbcH2 { } <4>
	r2dbcPostgresql {} <5>
}

val webConf = configuration { <1>
	beans { } <2>
	server { <6>
		engine = <7>
		port = <8>
		router { } <9>
		include() <10>
		coRouter { } <11>
		cors { } <12>
		codecs { } <13>
		mustache() <14>
		filter() <15>
	}
	client { <16>
		baseUrl = <17>
		codecs { } <18>
	}
}

val app = webApplication { <19>
	logging { } <20>
	configurationProperties<SampleProperties>() <21>
	listener<SampleEvent> { } <22>
	profile("sample"){ } <23>
	enable(dataConf) <24>
    enable(webConf) <24>
}

fun main() {
	app.run() <25>
}
```
<1> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-configuration-dsl/index.html[configuration documentation]
<2> {framework-kdoc-url}/spring-framework/org.springframework.context.support/-bean-definition-dsl/index.html[beans documentation]
<3> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.mongo/-mongo-dsl/index.html[mongo documentation]
<4> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.r2dbc/r2dbc-h2.html[r2dbc-h2 documentation]
<5> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.r2dbc/r2dbc-postgresql.html[r2dbc-postgresql documentation]
<6> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.web/-web-flux-server-dsl/index.html[WebFlux server documentation]
<7> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.web/-web-flux-server-dsl/engine.html[engine documentation]
<8> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.web/-web-flux-server-dsl/port.html[port documentation]
<9> {framework-kdoc-url}/spring-framework/org.springframework.web.reactive.function.server/-router-function-dsl/index.html[router documentation]
<10> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.web/-web-flux-server-dsl/co-router.html[Coroutines router documentation]
<11> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.web/-web-flux-server-dsl/include.html[Include router documentation]
<12> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.web/cors.html[cors documentation]
<13> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.web/-web-flux-server-dsl/-web-flux-server-codec-dsl/index.html[codecs documentation]
<14> {kofu-kdoc-url}/kofu/build/dokka/kofu/org.springframework.fu.kofu.web/mustache.html[mustache documentation]
<15> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.web/-web-flux-server-dsl/filter.html[filter documentation]
<16> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.web/-web-flux-client-dsl/index.html[WebFlux client documentation]
<17> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.web/-web-flux-client-dsl/base-url.html[baseUrl documentation]
<18> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu.web/-web-flux-client-dsl/-web-flux-client-codec-dsl/index.html[codecs documentation]
<19> {kofu-kdoc-url}/kofu/kofu/org.springframework.fu.kofu/-application-dsl/index.html[application/webApplication documentation]
<20> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-logging-dsl/index.html[logging documentation]
<21> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-configuration-dsl/configuration-properties.html[configuration-properties documentation]
<22> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-configuration-dsl/listener.html[listener-properties documentation]
<23> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-configuration-dsl/profile.html[profile-properties documentation]
<24> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-configuration-dsl/enable.html[enable documentation]
<25> {kofu-kdoc-url}/kofu/org.springframework.fu.kofu/-kofu-application/run.html[run documentation]

== Getting started

* Create a Spring `2.1.x` project on https://start.spring.io/#!language=kotlin[start.spring.io],
* Add the `org.springframework.fu:spring-fu-kofu:{spring-fu-version}` dependency
* Add the _Reactive Web_ `org.springframework.boot:spring-boot-starter-webflux` dependency
* Use latest Kotlin `1.3.x`
* Modify the generated `*Application.kt` file as following:

```kotlin
package com.sample

import org.springframework.fu.kofu.webApplication

val app = webApplication {
	server {
		router {
			GET("/") { ok().syncBody("Hello world!") }
		}
	}
}

fun main() {
	app.run()
}
```

== Samples

=== kofu-reactive-minimal

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-reactive-minimal[Browse source] |
http://repo.spring.io/milestone/org/springframework/fu/spring-fu-samples-kofu-reactive-minimal/{spring-fu-version}/spring-fu-samples-kofu-reactive-minimal-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot Reactive web application with Kofu configuration which provides a
`http://localhost:8080/` endpoint that displays "Hello world!" and an `http://localhost:8080/api` with a JSON
endpoint.

You can run compile and run it as a https://github.com/oracle/graal/tree/master/substratevm[Graal native image]
(GraalVM 1.0 RC10+) by running `./build.sh` then `./com.sample.applicationkt`.

=== kofu-reactive-mongodb

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-reactive-mongodb[Browse source] |
http://repo.spring.io/milestone/org/springframework/fu/spring-fu-samples-kofu-reactive-mongodb/{spring-fu-version}/spring-fu-samples-kofu-reactive-mongodb-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot Reactive web application with Kofu configuration and a Reactive MongoDB backend.

=== kofu-reactive-r2dbc

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-reactive-r2dbc[Browse source] |
http://repo.spring.io/milestone/org/springframework/fu/spring-fu-samples-kofu-reactive-r2dbc/{spring-fu-version}/spring-fu-samples-kofu-reactive-r2dbc-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot Reactive web application with Kofu configuration and a R2DBC backend.

=== kofu-coroutines-mongodb

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-coroutines-mongodb[Browse source] |
http://repo.spring.io/milestone/org/springframework/fu/spring-fu-samples-kofu-coroutines-mongodb/{spring-fu-version}/spring-fu-samples-kofu-coroutines-mongodb-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot Coroutines web application with Kofu configuration and a Reactive MongoDB backend.

=== kofu-coroutines-r2dbc

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-coroutines-r2dbc[Browse source] |
http://repo.spring.io/milestone/org/springframework/fu/spring-fu-samples-kofu-coroutines-r2dbc/{spring-fu-version}/spring-fu-samples-kofu-coroutines-r2dbc-{spring-fu-version}.zip[Download]

This is a sample project for a Spring Boot Coroutines web application with Kofu configuration and a R2DBC backend.