version: '3.1'
services:
  mysql-server:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/db/mysql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/main/resources/db/mysql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
  kofu-petclinic-jdbc:
    image: kofu-petclinic-jdbc:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - mysql-server