= Minimal webapp

This is a Spring Fu example of a minimal webapp with filtered classpath.

Spring Fu figures are:

 * Tomcat: 866 ms startup, 12.1 MB executable JAR, 3400 classes, 14 MB heap after startup without GC
 * Netty: 1058 ms startup, 12.6 MB  executable JAR, 3360 classes, 14 MB heap after startup without GC
 * Netty + Jackson: 1224 ms startup, 14.5 MB  executable JAR, 5200 classes, 65 MB heap after startup without GC

To be compared to Boot with Netty + Jackson via the default Web Reactive starter: 2263 ms startup, 20.6 MB  executable JAR, 7900 classes, 151 MB heap after startup without GC

TODO

 * Undertow: when https://github.com/spring-projects/spring-fu/issues/59 will be fixed
 * Jetty: when https://github.com/spring-projects/spring-fu/issues/60 will be fixed



The app could be benchmark with the following command:

`sudo perf stat -e cpu-clock -r10 java -jar -XX:TieredStopAtLevel=1 -noverify -Djava.security.egd=file:/dev/./urandom samples/minimal-webapp/build/libs/minimal-webapp-1.0.0.BUILD-SNAPSHOT-all.jar`


