= Minimal webapp

This is a Spring Fu example of a minimal webapp with filtered classpath used for startup time, memory, CPU and GC benchmarks.

The platform is `Openjdk 10.0.1` running on a Dell precision 5520 with `Linux 4.15.0-23-generic x86_64 GNU/Linux` (Ubuntu 18.04).

NOTE: Spring Boot 2.1 upcoming performance optimizations are likely to make functional configuration and `@Configuration` performances closer. The Boot application is a 2.0.3 Kotlin one with `spring-boot-starter-webflux` and `spring-boot-starter-json` excluded.


== Garbage collector

Spring Fu `-verbose:gc` logs are:

 [0.011s][info][gc] Using G1
 [0,494s][info][gc] GC(0) Pause Young (G1 Evacuation Pause) 24M->3M(500M) 2,955ms
 [0,898s][info][gc] GC(1) Pause Initial Mark (Metadata GC Threshold) 44M->6M(500M) 3,155ms
 [0,898s][info][gc] GC(2) Concurrent Cycle
 [0,901s][info][gc] GC(2) Pause Remark 7M->7M(500M) 1,614ms
 [0,901s][info][gc] GC(2) Pause Cleanup 7M->7M(500M) 0,183ms
 [0,903s][info][gc] GC(2) Concurrent Cycle 5,465ms
 Started in 0.719 seconds (JVM running for 0.963)


Spring Boot 2.0 `-verbose:gc` logs are:

 [0.006s][info][gc] Using G1
 [0,380s][info][gc] GC(0) Pause Young (G1 Evacuation Pause) 24M->2M(500M) 2,882ms
 [0,824s][info][gc] GC(1) Pause Initial Mark (Metadata GC Threshold) 86M->7M(500M) 5,057ms
 [0,824s][info][gc] GC(2) Concurrent Cycle
 [0,835s][info][gc] GC(2) Pause Remark 9M->9M(500M) 5,258ms
 [0,835s][info][gc] GC(2) Pause Cleanup 9M->9M(500M) 0,189ms
 [0,837s][info][gc] GC(2) Concurrent Cycle 12,718ms
 [1,480s][info][gc] GC(3) Pause Young (G1 Evacuation Pause) 119M->11M(500M) 8,935ms
 Started in 1.621 seconds (JVM running for 2.067)

== Startup time

== Netty

Spring Fu:

 Application started in 0.609 seconds (JVM running for 0.879)
 Application started in 0.676 seconds (JVM running for 0.97)
 Application started in 0.672 seconds (JVM running for 0.958)

Spring Boot 2.0:

 Started DemoStartupKotlinApplicationKt in 1.215 seconds (JVM running for 1.5)
 Started DemoStartupKotlinApplicationKt in 1.174 seconds (JVM running for 1.494)
 Started DemoStartupKotlinApplicationKt in 1.212 seconds (JVM running for 1.513)

=== Tomcat

Spring Fu:

 Application started in 0.440 seconds (JVM running for 0.709)
 Application started in 0.440 seconds (JVM running for 0.723)
 Application started in 0.445 seconds (JVM running for 0.72)

Spring Boot 2.0:

 Started DemoStartupKotlinApplicationKt in 1.228 seconds (JVM running for 1.538)
 Started DemoStartupKotlinApplicationKt in 1.262 seconds (JVM running for 1.561)
 Started DemoStartupKotlinApplicationKt in 1.262 seconds (JVM running for 1.561)

== Undertow

Spring Fu:

 Application started in 0.274 seconds (JVM running for 0.553)
 Application started in 0.268 seconds (JVM running for 0.508)
 Application started in 0.293 seconds (JVM running for 0.57)

Spring Boot 2.0:

 Started DemoStartupKotlinApplicationKt in 1.181 seconds (JVM running for 1.494)
 Started DemoStartupKotlinApplicationKt in 1.231 seconds (JVM running for 1.571)
 Started DemoStartupKotlinApplicationKt in 1.221 seconds (JVM running for 1.565)
