== Samples

=== jafu-reactive-minimal

https://github.com/spring-projects/spring-fu/tree/master/samples/jafu-reactive-minimal[Browse source]

This is a sample project for a Spring Boot Reactive web application with Jafu configuration which provides a
`http://localhost:8080/` endpoint that displays "Hello world!" and an `http://localhost:8080/api` with a JSON
endpoint.

=== jafu-reactive-r2dbc

https://github.com/spring-projects/spring-fu/tree/master/samples/jafu-reactive-r2dbc[Browse source]

This is a sample project for a Spring Boot Reactive web application with Jafu configuration and a R2DBC backend.

=== jafu-servlet-minimal

https://github.com/spring-projects/spring-fu/tree/master/samples/jafu-servlet-minimal[Browse source]

This is a sample project for a Spring Boot web application based on WebMvc.fn (functional variant of Spring MVC) with Kofu configuration which provides a
`http://localhost:8080/` endpoint that displays "Hello world!" and an `http://localhost:8080/api` with a JSON
endpoint.

=== kofu-reactive-minimal

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-reactive-minimal[Browse source]

This is a sample project for a Spring Boot Reactive web application with Kofu configuration which provides a
`http://localhost:8080/` endpoint that displays "Hello world!" and an `http://localhost:8080/api` with a JSON
endpoint.

=== kofu-reactive-mongodb

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-reactive-mongodb[Browse source]

This is a sample project for a Spring Boot Reactive web application with Kofu configuration and a Reactive MongoDB backend.

=== kofu-reactive-r2dbc

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-reactive-r2dbc[Browse source]

This is a sample project for a Spring Boot Reactive web application with Kofu configuration and a R2DBC backend.

=== kofu-reactive-validation

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-reactive-validation[Browse source]

This is a sample project for a Spring Boot Reactive web application with Kofu configuration and validation using https://github.com/making/yavi[YAVI].

=== kofu-coroutines-mongodb

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-coroutines-mongodb[Browse source]

This is a sample project for a Spring Boot Coroutines web application with Kofu configuration and a Reactive MongoDB backend.

=== kofu-coroutines-r2dbc

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-coroutines-r2dbc[Browse source]

This is a sample project for a Spring Boot Coroutines web application with Kofu configuration and a R2DBC backend.

=== kofu-coroutines-validation

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-coroutines-validation[Browse source]

This is a sample project for a Spring Boot Coroutines web application with Kofu configuration and validation using https://github.com/making/yavi[YAVI].

=== kofu-servlet-minimal

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-servlet-minimal[Browse source]

This is a sample project for a Spring Boot web application based on WebMvc.fn (functional variant of Spring MVC) with Kofu configuration which provides a
`http://localhost:8080/` endpoint that displays "Hello world!" and an `http://localhost:8080/api` with a JSON
endpoint.

=== kofu-servlet-validation

https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-servlet-validation[Browse source]

This is a sample project for a Spring Boot web application based on WebMvc.fn (functional variant of Spring MVC) with Kofu configuration and validation using https://github.com/making/yavi[YAVI].