:spring-fu-version: 0.3.0.M2
:jafu-javadoc-url: http://repo.spring.io/milestone/org/springframework/fu/spring-fu-jafu/{spring-fu-version}/spring-fu-jafu-{spring-fu-version}-javadoc.jar!
:framework-javadoc-url: https://docs.spring.io/spring-framework/docs/5.3.x/javadoc-api

image:https://img.shields.io/badge/Jafu%20API%20documentation-blue.svg["Jafu API documentation", link="{jafu-kdoc-url}/index.html"]

= Jafu DSL for Spring Boot

Jafu (for **Ja**va and **fu**nctional) is an alternative way of configuring explicitly your Spring Boot application,
different from regular auto-configuration, using a Java DSL. It is based on Spring Boot infrastructure, but
https://github.com/spring-projects/spring-fu/tree/master/autoconfigure-adapter[used via functional bean definitions]
instead of JavaConfig.

== API reference

An overview of Jafu DSL is provided bellow with the related {jafu-javadoc-url}/index.html[API documentation].
Be aware that a few static imports will be needed.

== Getting started

 * Create a Spring `2.3.0.M4` project on https://start.spring.io/[start.spring.io] with the "Reactive web" starter
 * Add the Spring milestone repository `https://repo.spring.io/snapshot`
 * Add the `org.springframework.fu:spring-fu-jafu:{spring-fu-version}` dependency
 * Modify the generated `DemoApplication.java` file as following:

```java
package com.sample;

import static org.springframework.fu.jafu.Jafu.application;
import static org.springframework.fu.jafu.webmvc.WebMvcServerDsl.webMvc;
import static org.springframework.web.servlet.function.ServerResponse..*;

import org.springframework.fu.jafu.JafuApplication;

public class DemoApplication {

	public static JafuApplication app = application(WebApplicationType.SERVLET, a ->
			a.enable(webMvc(s -> s.router(r ->
				r.GET("/", request -> ok().body("Hello world!"))
			)))
	);

	public static void main (String[] args) {
		app.run(args);
	}
}
```

See also sample projects https://github.com/spring-projects/spring-fu/tree/master/samples[here].
