resources:
  - name: spring-fu
    type: git
    source:
      uri: https://github.com/spring-projects/spring-fu
      branch: master
jobs:
  - name: build
    public: true
    plan:
    - get: spring-fu
      trigger: true
    - task: build
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: openjdk
            tag: 11-jdk
            username: ((docker-hub-username))
            password: ((docker-hub-password))
        inputs:
          - name: spring-fu
        run:
          path: spring-fu/ci/build.sh
  - name: deploy
    public: true
    plan:
    - get: spring-fu
      passed:
      - build
      trigger: true
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: openjdk
            tag: 11-jdk
            username: ((docker-hub-username))
            password: ((docker-hub-password))
        inputs:
          - name: spring-fu
        run:
          path: spring-fu/ci/deploy.sh
      params:
       ARTIFACTORY_USERNAME: ((artifactory_username))
       ARTIFACTORY_PASSWORD: ((artifactory_password))
